### ISSUE TITLE
如何调整被检测对象的类

### ISSUE THREAD

**Issue by KexuanXia** [RuoyuChen10/objectdetection-saliency-maps#10]
您好！

感谢您精彩的工作和分享！

我的研究方向是自动驾驶，所以我想调整检测对象的类，将您代码中的
`label_names = [
    'person bev', 'car bev', 'van bev', 'truck bev', 'bus bev',
    'person', 'car', 'aeroplane', 'bus', 'train', 'truck', 'boat',
    'bird', 'camouflage man'
]`
调整成
`label_names = [
    'person', 'car', 'cyclist'
]`
即保留person, car以及添加cyclist
但是我发现，label_names在[drise-yolov3.py](https://github.com/RuoyuChen10/objectdetection-saliency-maps/blob/a7d9b55a8d435d4aa0fdeab50d9b2b6c4bb40a0a/drise-yolov3.py)中被定义以后没有再使用过。

我在您提供的yolov3的配置文件yolo_v3.py中找到了以下代码：
`classes = ('person bev', 'car bev', 'van bev', 'bus bev', 'truck bev','aeroplane','train' , 'bird', 'boat', 'car', 'person', 'bus', 'truck','camouflage man')
`
这似乎是对yolov3的检测目标类的设置，但是我尝试更改它以及对应的num_classes，结果会导致代码的运行出现问题。

另外，如果我理解没有错误的话，yolov3目标检测器应该可以检测一共80种不同的类，您是如何将它调整成您代码中的14种的？恳请您提供一些建议或者思路。

谢谢！

**Comment by RuoyuChen10** [comment]
> 您好！
> 
> 感谢您精彩的工作和分享！
> 
> 我的研究方向是自动驾驶，所以我想调整检测对象的类，将您代码中的 `label_names = [ 'person bev', 'car bev', 'van bev', 'truck bev', 'bus bev', 'person', 'car', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'bird', 'camouflage man' ]` 调整成 `label_names = [ 'person', 'car', 'cyclist' ]` 即保留person, car以及添加cyclist 但是我发现，label_names在[drise-yolov3.py](https://github.com/RuoyuChen10/objectdetection-saliency-maps/blob/a7d9b55a8d435d4aa0fdeab50d9b2b6c4bb40a0a/drise-yolov3.py)中被定义以后没有再使用过。
> 
> 我在您提供的yolov3的配置文件yolo_v3.py中找到了以下代码： `classes = ('person bev', 'car bev', 'van bev', 'bus bev', 'truck bev','aeroplane','train' , 'bird', 'boat', 'car', 'person', 'bus', 'truck','camouflage man') ` 这似乎是对yolov3的检测目标类的设置，但是我尝试更改它以及对应的num_classes，结果会导致代码的运行出现问题。
> 
> 另外，如果我理解没有错误的话，yolov3目标检测器应该可以检测一共80种不同的类，您是如何将它调整成您代码中的14种的？恳请您提供一些建议或者思路。
> 
> 谢谢！

你好，我是用自己训练的yolo v3，不是官方的，所以是14个类。你可以下载官方的权重，我的权重也发布了，你看看readme里面的huggingface链接。

**Comment by KexuanXia** [comment]
您好！

感谢您的回复！

也就是说，如果我想用别的检测模型或者是调整检测模型的检测目标类的话，要替换掉您代码中的yolo v3。我需要自己训练或者下载训练好的其他模型并嵌入您的代码中。请问我这样理解对吗？

谢谢！

**Comment by RuoyuChen10** [comment]
> 您好！
> 
> 感谢您的回复！
> 
> 也就是说，如果我想用别的检测模型或者是调整检测模型的检测目标类的话，要替换掉您代码中的yolo v3。我需要自己训练或者下载训练好的其他模型并嵌入您的代码中。请问我这样理解对吗？
> 
> 谢谢！

如果模型还是yolo v3的话，只是类别和参数变了的话，应该只要改一个配置文件即可。

**Comment by KexuanXia** [comment]
好的，再次感谢您的解答和帮助！
