### ISSUE TITLE
neck可视化问题

### ISSUE THREAD

**Issue by 6991saltA** [RuoyuChen10/objectdetection-saliency-maps#9]
你好，我用你的代码改了swin transformer各阶段特征图的可视化，请问FPN融合后的各层级特征图能可视化吗，就是fpn_convs后的特征图？
我尝试改了，但是和swin transformer生成的特征图一模一样，可以指导下吗？
感谢！

**Comment by RuoyuChen10** [comment]
> 你好，我用你的代码改了swin transformer各阶段特征图的可视化，请问FPN融合后的各层级特征图能可视化吗，就是fpn_convs后的特征图？ 我尝试改了，但是和swin transformer生成的特征图一模一样，可以指导下吗？ 感谢！

你好，这个可能需要看看梯度能不能回传到那里吧，版本挺重要的，我这个主要就是改了很多不能梯度回传的地方。我最近忙投稿，可能暂时没时间看swin transformer相关的内容，因为我对这个backbone的应用其实并不是很熟悉。

**Comment by 6991saltA** [comment]
抱歉，最近写毕业论文忘了回复，感谢！
